# Generated by Django 4.2.7 on 2023-11-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=40)),
                ('thema', models.CharField(choices=[('useful', 'お役立ち情報'), ('diseases', '病気・障害について'), ('learning', '学習情報'), ('others', 'その他')], max_length=100)),
                ('text', models.TextField(blank=True)),
                ('url_link', models.URLField(blank=True)),
                ('attached_file', models.FileField(blank=True, upload_to='')),
                ('approved_or_not', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('edited_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
