# Generated by Django 4.2.7 on 2023-12-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_theme_label_alter_theme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='label',
            field=models.CharField(max_length=40),
        ),
    ]
