# Generated by Django 4.2.7 on 2023-11-21 12:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='attachment/', validators=[main.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
