# Generated by Django 4.2.7 on 2023-11-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_attached_file_alter_article_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('UNAPPROVED', '未承認'), ('APPROVED', '承認済'), ('DELETED', '削除済')], default='UNAPPROVED', max_length=10),
        ),
    ]
