# Generated by Django 4.2.7 on 2023-11-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', '未承認'), ('APPROVED', '承認済'), ('DELETED', '削除済')], default='DRAFT', max_length=10),
        ),
    ]
