# Generated by Django 4.2.7 on 2023-11-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.CharField(choices=[('useful', 'お役立ち情報'), ('diseases', '病気・障害について'), ('learning', '学習情報'), ('others', 'その他')], default='others', max_length=100),
            preserve_default=False,
        ),
    ]
