# Generated by Django 4.2.7 on 2023-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_article_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thema',
            field=models.CharField(choices=[('useful', 'お役立ち情報'), ('diseases', '病気・障害について'), ('learning', '学習情報'), ('OTHERS', 'その他')], max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.CharField(choices=[('useful', 'お役立ち情報'), ('diseases', '病気・障害について'), ('learning', '学習情報'), ('OTHERS', 'その他')], max_length=100),
        ),
    ]
