# Generated by Django 4.2.7 on 2023-11-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_article_thema_alter_article_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thema',
        ),
    ]
