# Generated by Django 4.2.7 on 2023-11-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_article_thema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='approved_or_not',
        ),
    ]
