# Generated by Django 4.2.7 on 2023-11-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_article_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='passcode',
            field=models.IntegerField(blank=True, default=9999),
            preserve_default=False,
        ),
    ]
