# Generated by Django 4.2.7 on 2023-11-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_article_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='passcode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
