# Generated by Django 4.2.7 on 2023-11-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_article_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', '未承認'), ('APPROVED', '承認済'), ('DELETED', '削除済')], default='DRAFT', max_length=10),
        ),
    ]
